apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: nayab786/github-actions:main-34266b3
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
